
version: '3'
services:

  api:
    image: cinthyareboucas/app_fastdata
    ports:
      - "4000:5000"
    depends_on:
      - mysql
    deploy:
      replicas: 3
      mode: replicated
      restart_policy:
       condition: on-failure

  mysql:
    image: cinthyareboucas/mysql_fastdata
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: senhaFiap
    deploy:
      replicas: 1
      restart_policy:
       condition: on-failure
